version: '2.2'
services:
  app:
    build: .
    command: npm run dev:buid
    volumes:
      - .:/src/tmp/
      - /src/tmp/node_modules
    ports:
      - "8080:8080"
    links:
      - mongo
  mongo:
    container_name: mongoDB
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
